name: CI - Master - Lint and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-test:

    strategy:
      matrix:
        node-version: ['22.11.0']

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Use Yarn 4.4.0
        run: corepack prepare yarn@4.4.0 --activate

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Linter
        run: yarn rw lint

      - name: Run Tests
        run: yarn rw test
